pizza_app/urls.py
from django.urls import path

from pizza_app.views import create, view, close, stats

app_name = 'pizza_app'

urlpatterns = [
    path('create/', create, name='create'),
    # # view/<int:pizza_order_id>
    path('view/<int:pizza_order_id>/', view, name='view'),
    path('close/<int:pizza_order_id>/', close, name='close'),
    #
    path('stats/', stats, name='stats'),
]

pizza_auth_app/urls.py
from django.urls import path

from django.contrib.auth.views import logout_then_login, LoginView
from django.views.generic import CreateView

from pizza_auth_app.forms import CustomCreationForm

app_name = 'pizza_auth_app'

urlpatterns = [
    path('login/', LoginView.as_view(
        template_name='auth_app/login.html'
    ), name='login'),

    path('logout/', logout_then_login, name='logout'),

    path('register/', CreateView.as_view(
        template_name='auth_app/register.html',
        form_class=CustomCreationForm,
        success_url='/',
    ), name='register'),
]

pizza_project/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

from pizza_app import urls as pizza_urls
from pizza_auth_app import urls as pizza_auth_urls
from pizza_app.views import index

urlpatterns = [
    path('admin/', admin.site.urls),

    path('auth/', include(pizza_auth_urls, namespace='auth_app')),
    path('pizza/', include(pizza_urls, namespace='pizza')),

    path('', index, name='index'),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

pizza_auth_app/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class CustomUser(AbstractUser):
    favourite_pizza = models.ForeignKey(
        'pizza_app.PizzaMenuItem', null=True, default=None, blank=True, on_delete=models.PROTECT)

    our_note = models.CharField(max_length=140, blank=True)

pizza_auth_app/forms.py
# -*- coding: utf-8 -*-
from django.contrib.auth.forms import UserCreationForm

from pizza_auth_app.models import CustomUser


class CustomCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ('username', )

pizza_auth_app/views.py
from django.shortcuts import render_to_response

# Create your views here.

pizza_auth_app/templates/auth_app/login.html
{% extends 'pizza_app/_base.html' %}

{% block content %}

<h1>Hello. Log in, please!</h1>

<form action="{% url 'auth_app:login' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>


{% endblock %}

pizza_auth_app/templates/auth_app/register.html
{% extends 'pizza_app/_base.html' %}

{% block content %}

<h1>Register, please!</h1>

<form action="{% url 'auth_app:register' %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>

{% endblock %}